### ISSUE TITLE
impossible to clone ticket

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/escalade#12] opened 2016-05-13 15:15 UTC
Hello

Nothing happens when I click on clone ticket

glpi 0.90.3 - iis 8.5

**Comment by satyan01** [comment] 2016-10-25 12:34
![image](https://cloud.githubusercontent.com/assets/15144026/19686110/17959886-9ac0-11e6-9f50-b035f981349e.png)

**Comment by trasher** [comment] 2016-10-25 12:47
Hum... Sounds like an issue with the ticket, and not the plugin.

Are you able to edit the initial ticket you want to clone, without GLPi asking for something missing?

**Comment by satyan01** [comment] 2016-10-25 12:49
yes no problem with tickets

**Comment by Guanymede** [comment] 2016-12-21 17:06
Hello, I have the same issue.
When I click on the icon, nothing happens. Then when I edit and save the current ticket I want to clone, it works but I get a message in the infobox : "requester is mandatory". And nothing more
GLPI 0.90.3
Escalade plugin	0.90-1.1
Any solution ?
thanks !

**Comment by amma35** [comment] 2018-03-12 15:33
same problem, this is a conflict with the plugin behaviors

Indeed in behaviors plugin, a check is done on the' alternative_email' variable whereas in ticket cloning, this value is not indicated :
`&& (!isset($ticket->input['_users_id_requester_notif']['alternative_email']) `

I added this variable when cloning like this:
```
diff --git a/inc/ticket.class.php b/inc/ticket.class.php
index 9b37c88..3ac1e32 100644
--- a/inc/ticket.class.php
+++ b/inc/ticket.class.php
@@ -599,6 +599,7 @@ class PluginEscaladeTicket {
       $fields = array_map(array('Toolbox', 'addslashes_deep'), $fields);
       $fields['id']                  = 0;
       $fields['_users_id_requester'] = 0;
+      $fields['_users_id_requester_notif']['alternative_email'] = [0];
       $fields['status']              = CommonITILObject::INCOMING;
```

**Comment by stonebuzz** [comment] 2020-01-21 10:32
hi @wawax 
Hi @satyan01 
This problem hasn't changed in a long time.

I am closing this file, feel free to continue the discussion here if you wish or to reopen if the problem is still present.

**Closed by stonebuzz** 2020-01-21 10:32 UTC
Labels: bug
