### ISSUE TITLE
Rapid ticket assignation improvments

### ISSUE THREAD

**Issue by wawax** [pluginsGLPI/escalade#3] opened 2015-05-12 15:41 UTC
Original ticket on Redmine : https://forge.glpi-project.org/issues/4210

**Comment by stonebuzz** [comment] 2020-01-21 10:31
hi @wawax 

This problem hasn't changed in a long time.

I am closing this file, feel free to continue the discussion here if you wish or to reopen if the problem is still present.

**Closed by stonebuzz** 2020-01-21 10:31 UTC
Labels: enhancement
