### ISSUE TITLE
Fatal error: Uncaught Error: Class 'PluginEscaladeConfig' not found

### ISSUE THREAD

**Issue by alexsrb** [pluginsGLPI/escalade#43] opened 2018-01-13 03:13 UTC
Hi,

My environment is characterized by the following versions:
- GLPI 9.2.1
- Escalade 2.2.1

When the Escalade plugin is enabled and I access the 'plugins' page, the following error is displayed with GLPI in debug mode:

Fatal error: Uncaught Error: Class 'PluginEscaladeConfig' not found in [redacted path]\glpi\plugins\escalade\setup.php:49 Stack trace: #0 [redacted path]\glpi\inc\plugin.class.php(145): plugin_init_escalade() #1 [redacted path]\glpi\inc\plugin.class.php(418): Plugin::load('escalade', true) #2 [redacted path]\glpi\front\plugin.php(95): Plugin->listPlugins() #3 {main} thrown in [redacted path]\glpi\plugins\escalade\setup.php on line 49

**Comment by cedric-anne** [comment] 2018-06-05 07:51
Hi,

As I cannot reproduce this issue, I close it.

Regards

**Closed by cedric-anne** 2018-06-05 07:51 UTC
Labels: bug
