### ISSUE TITLE
Options "Use the technician's group" and "Remove technician(s) on escalation" don't work well when both are "on"

### ISSUE THREAD

**Issue by grajek** [pluginsGLPI/escalade#15] opened 2016-07-29 09:29 UTC
Hello!
When "Use the technician's group" is on and "Remove technician(s) on escalation" is on and there is a technician that belongs to more than one groups, then loop may occurr.
Scenario:
- technician belongs to groups "A" and "B",
- "Use the technician's group" is set to "first",
- "Remove technician(s) on escalation" is set,
- ticket is assigned to group "B",
- technician wants to be assigned to this ticket, no change to group should occur.

Under this scenario, technician's goal is impossible to achieve. When he assigns himself to a ticket, then group "B" is replaced with group "A". Next, when he assigns group "B" to a ticket, then he is deleted from a ticket.

Proposition:
When a ticket is escalated to a different group, and assigned technician is a member of this group, then technician should not be removed from a ticket.

**Comment by stonebuzz** [comment] 2020-01-21 10:31
Hi @grajek 

This problem hasn't changed in a long time.

I am closing this file, feel free to continue the discussion here if you wish or to reopen if the problem is still present.

**Closed by stonebuzz** 2020-01-21 10:31 UTC
Labels: bug
