### ISSUE TITLE
Plugin Escalade blocking change ticket actors

### ISSUE THREAD

**Issue by pcabrera991** [pluginsGLPI/escalade#8] opened 2016-01-12 20:53 UTC
Please your help with this issue http://forum.glpi-project.org/viewtopic.php?id=127601

**Comment by stonebuzz** [comment] 2020-01-21 10:32
hi @pcabrera991  

This problem hasn't changed in a long time.

I am closing this file, feel free to continue the discussion here if you wish or to reopen if the problem is still present.

**Closed by stonebuzz** 2020-01-21 10:32 UTC
Labels: bug
