### ISSUE TITLE
Error: change of status of the ticket

### ISSUE THREAD

**Issue by amma35** [pluginsGLPI/escalade#13] opened 2016-06-29 10:24 UTC
After the creation of a ticket if I assign a group to the ticket when saving, it changes the ticket status in "New."

In the plugin configuration: Ticket status after climbing -> no change
There is the same mistake if I put the current status (planned)

![capture](https://cloud.githubusercontent.com/assets/15138371/16448894/4a045588-3df4-11e6-914c-08947671ac8a.PNG)

**Comment by orthagh** [comment] 2016-12-07 09:03
Hello @amma35 

This issue is old but could you confirm it's still valid and the version you encountered the bug

**Comment by PierreTeclib** [comment] 2016-12-23 08:40
Confirm with this versions:

GLPI : 0.90.5
Plugin : 0.90-1.2

**Comment by trasher** [comment] 2016-12-27 08:00
I think I've reproduced the issue (with latest develop); but I do not know how to solve that...

The line https://github.com/pluginsGLPI/escalade/blob/master/inc/ticket.class.php#L413 from the plugin will call this code from the core: https://github.com/glpi-project/glpi/blob/master/inc/commonitilactor.class.php#L303

At this point, the "if" is not satisfied; and therefore status is changed back to 1.

**Comment by jstival** [comment] 2017-01-17 22:29
Je suis en version 9.1 avec la version 2.1.0 du plugin, lorsque je mets la valeur "Statut du ticket après une escalade" = En attente, il ne change pas le statut du ticket lors d'une escalade (sans doute pour les raisons évoqués plus haut.

**Comment by lolokai** [comment] 2017-03-15 06:07
UP

**Comment by stonebuzz** [comment] 2020-01-21 10:33
hi @amma35  

This problem hasn't changed in a long time.

I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present.

**Closed by stonebuzz** 2020-01-21 10:33 UTC
Labels: bug

**Comment by rpauleau** [comment] 2020-02-27 12:49
Hi,

I have the same problem

**Comment by stonebuzz** [comment] 2020-02-27 13:06
Hi can you open new issue and provide us more informations ?

GLPI version, plugin version, step to reproduce, screenshot, plugin configuration

Best regards

**Comment by rpauleau** [comment] 2020-02-27 13:12
yep => https://github.com/pluginsGLPI/escalade/issues/87
